@startuml IEnumerableExtensions.ForEach
title IEnumerableExtensions.ForEach
start
if (source != null && action != null) then (<color:green>yes)
    :iterator = source.GetIterator();
    while (iterator.MoveNext()) is (<color:green>yes)
    :current = iterator.Current();
              :action(current);
    endwhile (<color:red>no)
endif
#Lavender:return source ?? [];
stop
@enduml
