@startuml IEnumerableExtensions.FindIndex
title IEnumerableExtensions.FindIndex
start
#LightBlue:int retVal = 0;
:iterator = items.GetIterator();
while (iterator.MoveNext()) is (<color:green>yes)
:current = iterator.Current();
      if (predicate(current)) then (<color:green>yes)
        #Lavender:return retVal;
      endif
      :retVal++;
endwhile (<color:red>no)
#Lavender:return -1;
stop
@enduml
