@startuml IEnumerableExtensions.Flatten
title IEnumerableExtensions.Flatten
start
#LightBlue:List<ST> expandResult = [];
if (source != null && expandSelector != null) then (<color:green>yes)
    :iterator = source.GetIterator();
    while (iterator.MoveNext()) is (<color:green>yes)
    :current = iterator.Current();
              #LightBlue:var subItems = expandSelector(current);
              if (subItems != null) then (<color:green>yes)
                  :expandResult.AddRange(subItems);
              endif
    endwhile (<color:red>no)
endif
#Lavender:return expandResult;
stop
@enduml
