@startuml IEnumerableExtensions.ToEnumerable
title IEnumerableExtensions.ToEnumerable
start
#LightBlue:List<ST> expandResult = [];
if (source != null && expandSelector != null) then (<color:green>yes)
    :iterator = source.GetIterator();
    while (iterator.MoveNext()) is (<color:green>yes)
    :current = iterator.Current();
              #LightBlue:var subItem = expandSelector(current);
              if (subItem != null) then (<color:green>yes)
                  :expandResult.Add(subItem);
              endif
    endwhile (<color:red>no)
endif
#Lavender:return expandResult;
stop
@enduml
