@startuml StringExtensions.ToFileName
title StringExtensions.ToFileName
start
:iterator = Path.GetInvalidFileNameChars().GetIterator();
while (iterator.MoveNext()) is (<color:green>yes)
:current = iterator.Current();
      :text = text.Replacurrente(current, '_');
endwhile (<color:red>no)
#Lavender:return text ?? String.Empty;
stop
@enduml
