@startuml StringExtensions.Substring
title StringExtensions.Substring
start
#LightBlue:var result = string.Empty
var ofIdx = source.IndexOf(text);
if (ofIdx >= 0 && ofIdx - index >= 0) then (<color:green>yes)
    :result = source.Substring(index, ofIdx);
endif
#Lavender:return result;
stop
@enduml
