@startuml StringExtensions.RemoveAll
title StringExtensions.RemoveAll
start
#LightBlue:var result = source;
:iterator = removeItems.GetIterator();
while (iterator.MoveNext()) is (<color:green>yes)
:current = iterator.Current();
      :result = result.Replace(current, string.Empty);
endwhile (<color:red>no)
#Lavender:return result;
stop
@enduml
