@startuml StringExtensions.ToByteArray
title StringExtensions.ToByteArray
start
#LightBlue:byte[]? result = null;
if (source != null) then (<color:green>yes)
    :result = new ASCIIEncoding().GetBytes(source);
endif
#Lavender:return result ?? [];
stop
@enduml
