@startuml StringExtensions.ReplaceUmlauts
title StringExtensions.ReplaceUmlauts
start
#LightBlue:StringBuilder sb = new();
if (text != null) then (<color:green>yes)
    :iterator = text.GetIterator();
    while (iterator.MoveNext()) is (<color:green>yes)
    :current = iterator.Current();
              if (current == 223) then (<color:green>yes)
                  :sb.Append("ss");
                else (<color:red>no)
                  if (current == 196) then (<color:green>yes)
                      :sb.Append("Ae");
                    else (<color:red>no)
                      if (current == 228) then (<color:green>yes)
                          :sb.Append("ae");
                        else (<color:red>no)
                          if (current == 214) then (<color:green>yes)
                              :sb.Append("Oe");
                            else (<color:red>no)
                              if (current == 246) then (<color:green>yes)
                                  :sb.Append("oe");
                                else (<color:red>no)
                                  if (current == 220) then (<color:green>yes)
                                      :sb.Append("Ue");
                                    else (<color:red>no)
                                      if (current == 252) then (<color:green>yes)
                                          :sb.Append("ue");
                                        else (<color:red>no)
                                            :sb.Append(current);
                                      endif
                                  endif
                              endif
                          endif
                      endif
                  endif
              endif
    endwhile (<color:red>no)
endif
#Lavender:return sb.ToString();
stop
@enduml
