@startuml StringExtensions.ExtractBetween
title StringExtensions.ExtractBetween
start
#LightBlue:var toScan = true
var open = false
var openCount = 0
var result = new StringBuilder();
#LightBlue:int i = startPosition;
while (i > -1 && i < source.Length && toScan) is (<color:green>yes)
    if (source[i] == openingBracket && open == false) then (<color:green>yes)
        :open = true;
        :openCount = 1;
      else (<color:red>no)
        if (source[i] == openingBracket && open) then (<color:green>yes)
            :openCount++;
            :result.Append(source[i]);
          else (<color:red>no)
            if (source[i] == closingBracket && openCount > 1) then (<color:green>yes)
                :openCount--;
                :result.Append(source[i]);
              else (<color:red>no)
                if (source[i] == closingBracket && openCount == 1) then (<color:green>yes)
                    :open = false;
                    :openCount = 0;
                    :toScan = false;
                  else (<color:red>no)
                    if (openCount > 0) then (<color:green>yes)
                        :result.Append(source[i]);
                    endif
                endif
            endif
        endif
    endif
:i++;
endwhile (<color:red>no)
#Lavender:return toScan == false ? result.ToString() : string.Empty;
stop
@enduml
