@startuml StringExtensions.Contains
title StringExtensions.Contains
start
#LightBlue:var result = false
var search = quotationStarts.Length == quotationEnds.Length
var quotationCounter = new int[quotationStarts.Length];
#LightBlue:int i = 0;
while (i < source.Length && search) is (<color:green>yes)
    #LightBlue:var c = source[i];
    if (quotationStarts.FindIndex(q => q == c) > -1) then (<color:green>yes)
        :quotationCounter[quotationStarts.FindIndex(q => q == c)]++;
      else (<color:red>no)
        if (quotationEnds.FindIndex(q => q == c) > -1) then (<color:green>yes)
            :quotationCounter[quotationEnds.FindIndex(q => q == c)]--;
          else (<color:red>no)
            if (quotationCounter.Sum(q => q % 2) == 0) then (<color:green>yes)
                :result = c == toCheck;
                :search = result == false;
            endif
        endif
    endif
:i++;
endwhile (<color:red>no)
#Lavender:return result;
stop
@enduml
