@startuml Application.GetCurrentSolutionPath
title Application.GetCurrentSolutionPath
start
#LightBlue:var result = string.Empty
var paths = AppContext.BaseDirectory.Split(Path.DirectorySeparatorChar)
var checkPath = paths.Length > 0 && paths[0].IsNullOrEmpty() ? $"{Path.DirectorySeparatorChar}" : string.Empty
var index = paths.Length > 0 && paths[0].IsNullOrEmpty() ? 1 : 0;
while (result.IsNullOrEmpty() && index < paths.Length) is (<color:green>yes)
    #LightBlue:var folder = paths[index++];
    #LightBlue:var fileName = $"{folder}.sln";
    :checkPath = Path.Combine(checkPath, folder);
    #LightBlue:var filePath = Path.Combine(checkPath, fileName);
    if (File.Exists(filePath)) then (<color:green>yes)
        :result = checkPath;
    endif
endwhile (<color:red>no)
#Lavender:return result;
stop
@enduml
