@startuml ConsoleApplication.Run
title ConsoleApplication.Run
start
#LightGreen:Params(string[] args);
#LightSkyBlue:var choose = default(string[])\nvar saveForegrondColor = ForegroundColor;
#WhiteSmoke:BeforeRun(args);
#WhiteSmoke:RunApp = true;
repeat
        #WhiteSmoke:PrintScreen();
        #WhiteSmoke:choose = ReadLine().ToLower().Split(',', StringSplitOptions.RemoveEmptyEntries);
        #LightSkyBlue:var chooseIterator = choose.GetEnumerator();
        #WhiteSmoke:BeforeExecution();
        #WhiteSmoke:ForegroundColor = saveForegrondColor;
        while (RunApp && chooseIterator.MoveNext()) is (<color:green>yes)
                #LightSkyBlue:var actions = MenuItems.Where(m => m.IsDisplayed && (m.Key.Equals(chooseIterator.Current) || m.OptionalKey.Equals(chooseIterator.Current)));
                #LightSkyBlue:var actionIterator = actions.GetEnumerator();
                while (RunApp && actionIterator.MoveNext()) is (<color:green>yes)
                        #WhiteSmoke:actionIterator.Current?.Action(actionIterator.Current);
                endwhile (<color:red>no)
                #WhiteSmoke:RunApp = RunApp && chooseIterator.Current.Equals("x") == false;
                #WhiteSmoke:StopProgressBar();
        endwhile (<color:red>no)
        #WhiteSmoke:AfterExecution();
repeat while (RunApp) is (<color:green>yes)
#WhiteSmoke:AfterRun();
stop
@enduml
