@startuml ConsoleApplication.ToLabelText
title ConsoleApplication.ToLabelText
start
#LightGreen:Params(string label,string text,int width,char chr);
#LightSkyBlue:var diff = width - label.Length\nvar space = new string(chr, Math.Max(0, diff));
#Lavender:return $"{label}{space}{text}";
stop
@enduml
