@startuml ConsoleApplication.ChangeSourcePath
title ConsoleApplication.ChangeSourcePath
start
:PrintLine();
:Print("Enter source path: ");
#LightBlue:var newPath = ReadLine();
if (Directory.Exists(newPath)) then (<color:green>yes)
    :SourcePath = newPath;
endif
stop
@enduml
