@startuml ConsoleApplication.PrintHeader
title ConsoleApplication.PrintHeader
start
#LightBlue:var saveForeColor = ForegroundColor
var solutionPath = GetCurrentSolutionPath()
var solutionName = TemplatePath.GetSolutionNameFromPath(solutionPath);
:ForegroundColor = ConsoleColor.Green;
#LightBlue:var count = PrintLine(solutionName);
:PrintLine('=', count);
:PrintLine();
:ForegroundColor = saveForeColor;
:PrintLine($"Force flag:     {Force}");
:PrintLine();
stop
@enduml
