@startuml ConsoleApplication.ChangePath
title ConsoleApplication.ChangePath
start
:PrintLine();
:Print(title);
#LightBlue:var newPath = ReadLine();
if (Directory.Exists(newPath)) then (<color:green>yes)
    :path = newPath;
endif
#Lavender:return path;
stop
@enduml
