@startuml ConsoleApplication.StartProgressBar
title ConsoleApplication.StartProgressBar
start
#LightYellow:if (RunProgressBar == false) then (<color:green>yes)
        #LightSkyBlue:var head = '>';
        #LightSkyBlue:var runSign = '=';
        #LightSkyBlue:var counter = 0;
        #WhiteSmoke:RunProgressBar = true;
        #WhiteSmoke:PrintLine();
        #WhiteSmoke:var (Left, Top) = GetCursorPosition();
        #WhiteSmoke:PrintLine();
        #WhiteSmoke:PrintLine();
        #WhiteSmoke:Task.Factory.StartNew(async () =>
                {
                    while (RunProgressBar)
                    {
                        if (CanProgressBarPrint)
                        {
                            if (Left > 65)
                            {
                                var timeInSec = counter / 5;

                                for (int i = 0; i <= Left; i++)
                                {
                                    Write(i, Top, " ");
                                }
                                Left = 0;
                            }
                            else
                            {
                                Write(Left++, Top, $"{runSign}{head}");
                            }

                            if (counter % 5 == 0)
                            {
                                Write(65, Top, $"{counter / 5,5} [sec]");
                            }
                        }
                        counter++;
                        await Task.Delay(200);
                    }
                });
endif
stop
@enduml
