@startuml StringExtensions.SetIndent
title StringExtensions.SetIndent
start
#LightGreen:Params(this string text,string indentSpace,int count);
#LightSkyBlue:StringBuilder sb = new();
#LightYellow:if (text != null) then (<color:green>yes)
        #LightSkyBlue:int i = 0;
        while (i < count) is (<color:green>yes)
            #WhiteSmoke:sb.Append(indentSpace);
        :i++;
        endwhile (<color:red>no)
endif
#WhiteSmoke:sb.Append(text);
#Lavender:return sb.ToString();
stop
@enduml
