@startuml StringExtensions.AreEquals
title StringExtensions.AreEquals
start
#LightGreen:Params(this string source,string value);
#Lavender:return source == null && value == null || value != null && source != null && source.Equals(value);
stop
@enduml
