@startuml StringExtensions.ExtractBetween
title StringExtensions.ExtractBetween
start
#LightGreen:Params(this string source,char openingBracket,char closingBracket);
#Lavender:return source.ExtractBetween(openingBracket, closingBracket, 0);
stop
@enduml
