@startuml TemplatePath.GetProjectSubFilePath
title TemplatePath.GetProjectSubFilePath
start
#LightGreen:Params(string filePath);
#LightSkyBlue:var subPath = GetSolutionItemDataFromPath(filePath, ".csproj").SubPath\nvar result = filePath!.Replace(subPath, string.Empty);
#LightYellow:if (result.StartsWith(Path.DirectorySeparatorChar)) then (<color:green>yes)
        #WhiteSmoke:result = result[1..];
endif
#Lavender:return result;
stop
@enduml
