@startuml TemplatePath.GetProjectNameFromPath
title TemplatePath.GetProjectNameFromPath
start
#LightGreen:Params(string path);
#Lavender:return GetSolutionItemDataFromPath(path, ".csproj").Name;
stop
@enduml
