@startuml TemplatePath.GetTemplateParentPaths
title TemplatePath.GetTemplateParentPaths
start
#LightBlue:var result = new List<string>()
var qtProjects = GetTemplatePaths(startPath).Union(includePaths).ToArray()
var qtPaths = qtProjects.Select(p => GetParentDirectory(p))
                                    .Distinct()
                                    .OrderBy(p => p);
:iterator = qtPaths.GetIterator();
while (iterator.MoveNext()) is (<color:green>yes)
:current = iterator.Current();
      if (result.Any(x => current.Length > x.Length && current.Contains(x)) == false) then (<color:green>yes)
          :result.Add(current);
      endif
endwhile (<color:red>no)
#Lavender:return [.. result];
stop
@enduml
