@startuml TemplatePath.OpenSolutionFolder
title TemplatePath.OpenSolutionFolder
start
if (Environment.OSVersion.Platform == PlatformID.Win32NT) then (<color:green>yes)
    :Process.Start(new ProcessStartInfo()
                {
                    WorkingDirectory = solutionPath,
                    FileName = "explorer",
                    Arguments = solutionPath,
                    CreateNoWindow = true,
                });
endif
stop
@enduml
