@startuml TemplatePath.GetPathFromPath
title TemplatePath.GetPathFromPath
start
#LightBlue:var result = string.Empty
var checkPath = path.StartsWith(Path.DirectorySeparatorChar) ? Path.DirectorySeparatorChar.ToString() : string.Empty
var data = path.Split(Path.DirectorySeparatorChar, StringSplitOptions.RemoveEmptyEntries);
#LightBlue:int i = 0;
while (i < data.Length && result == string.Empty) is (<color:green>yes)
    :checkPath = Path.Combine(checkPath, data[i]);
    #LightBlue:var projectFilePath = Path.Combine(checkPath, $"{data[i]}{checkFileExtension}");
    if (File.Exists(projectFilePath)) then (<color:green>yes)
        :result = checkPath;
    endif
:i++;
endwhile (<color:red>no)
#Lavender:return result;
stop
@enduml
