@startuml Application.GetParentFromPath
title Application.GetParentFromPath
participant "GetParentFromPath(string path)" as GetParentFromPath_p0 #LightYellow
participant "Directory.GetParent(a0)" as Directory_GetParent_a0 #LightGreen
autonumber
GetParentFromPath_p0 -[#grey]> Directory_GetParent_a0 : (path)
Directory_GetParent_a0 -[#blue]-> GetParentFromPath_p0 : result
@enduml
