@startuml StringExtensions.CuttingOut
title StringExtensions.CuttingOut
participant "CuttingOut(this string source,int startIdx)" as CuttingOut_p0_p1 #LightYellow
participant "source.CuttingOut(a0,a1)" as source_CuttingOut_a0_a1 #LightGreen
autonumber
CuttingOut_p0_p1 -[#grey]> source_CuttingOut_a0_a1 : (startIdx, source.Length - 1)
source_CuttingOut_a0_a1 -[#blue]-> CuttingOut_p0_p1 : result
@enduml
