@startuml StringExtensions.CreatePluralWord
title StringExtensions.CreatePluralWord
participant "CreatePluralWord(this string wordInSingular)" as CreatePluralWord_p0 #LightYellow
participant "wordInSingular.IsWord()" as wordInSingular_IsWord #LightGreen
participant "wordInSingular.EndsWith(a0,a1)" as wordInSingular_EndsWith_a0_a1 #LightGreen
autonumber
alt#LightBlue wordInSingular.IsWord()
    CreatePluralWord_p0 -[#grey]> wordInSingular_IsWord
    wordInSingular_IsWord -[#blue]-> CreatePluralWord_p0 : result
    alt#LightBlue wordInSingular.EndsWith("y", StringComparison.CurrentCultureIgnoreCase)
        CreatePluralWord_p0 -[#grey]> wordInSingular_EndsWith_a0_a1 : ("y", StringComparison.CurrentCultureIgnoreCase)
        else
            alt#LightBlue wordInSingular.EndsWith("h", StringComparison.CurrentCultureIgnoreCase)
                CreatePluralWord_p0 -[#grey]> wordInSingular_EndsWith_a0_a1 : ("h", StringComparison.CurrentCultureIgnoreCase)
                else
                    alt#LightBlue wordInSingular.EndsWith("x", StringComparison.CurrentCultureIgnoreCase)
                        CreatePluralWord_p0 -[#grey]> wordInSingular_EndsWith_a0_a1 : ("x", StringComparison.CurrentCultureIgnoreCase)
                        else
                            alt#LightBlue wordInSingular.EndsWith("f", StringComparison.CurrentCultureIgnoreCase)
                                CreatePluralWord_p0 -[#grey]> wordInSingular_EndsWith_a0_a1 : ("f", StringComparison.CurrentCultureIgnoreCase)
                                else
                                    alt#LightBlue wordInSingular.EndsWith("ss", StringComparison.CurrentCultureIgnoreCase)
                                        CreatePluralWord_p0 -[#grey]> wordInSingular_EndsWith_a0_a1 : ("ss", StringComparison.CurrentCultureIgnoreCase)
                                        else
                                            alt#LightBlue wordInSingular.EndsWith("s", StringComparison.CurrentCultureIgnoreCase)
                                                CreatePluralWord_p0 -[#grey]> wordInSingular_EndsWith_a0_a1 : ("s", StringComparison.CurrentCultureIgnoreCase)
                                            end
                                    end
                            end
                    end
            end
    end
end
@enduml
