@startuml StringExtensions.SetIndent
title StringExtensions.SetIndent
participant "SetIndent(this string text)" as SetIndent_p0 #LightYellow
participant "text.SetIndent(a0,a1)" as text_SetIndent_a0_a1 #LightGreen
autonumber
SetIndent_p0 -[#grey]> text_SetIndent_a0_a1 : (IndentSpace, 1)
text_SetIndent_a0_a1 -[#blue]-> SetIndent_p0 : result
@enduml
