@startuml StringExtensions.ToLong
title StringExtensions.ToLong
participant "ToLong(this string text)" as ToLong_p0 #LightYellow
participant "char.IsDigit(a0)" as char_IsDigit_a0 #LightGreen
autonumber
loop#LightCoral text
    alt#LightBlue char.IsDigit(item)
        ToLong_p0 -[#grey]> char_IsDigit_a0 : (item)
        char_IsDigit_a0 -[#blue]-> ToLong_p0 : result
    end
end
@enduml
