@startuml StringExtensions.AreEquals
title StringExtensions.AreEquals
participant "AreEquals(this string source,string value,StringComparison stringComparison)" as AreEquals_p0_p1_p2 #LightYellow
participant "source.Equals(a0,a1)" as source_Equals_a0_a1 #LightGreen
autonumber
AreEquals_p0_p1_p2 -[#grey]> source_Equals_a0_a1 : (value, stringComparison)
@enduml
