@startuml TemplatePath.GetProjectNameFromPath
title TemplatePath.GetProjectNameFromPath
participant "GetProjectNameFromPath(string path)" as GetProjectNameFromPath_p0 #LightYellow
participant "GetSolutionItemDataFromPath(a0,a1)" as GetSolutionItemDataFromPath_a0_a1 #LightGreen
autonumber
GetProjectNameFromPath_p0 -[#grey]> GetSolutionItemDataFromPath_a0_a1 : (path, ".csproj")
GetSolutionItemDataFromPath_a0_a1 -[#blue]-> GetProjectNameFromPath_p0 : result
@enduml
